name: JupyterLab UI Profiler

on:
  workflow_dispatch:
    inputs:
      challenger:
        description: "JupyterLab Git repository with the challenger version (format {owner}/{repo})"
        required: true
      challenger_branch:
        description: "Git repository reference to the challenger branch"
        required: true
      challenger_project:
        description: "Playwright project to execute (windowingMode JupyterLab 4; renderCellOnIdle: JupyterLab 2.3 or 3.x)"
        required: false
        default: "jupyterlab"
        type: choice
        options:
          - jupyterlab
          - jupyterlab-renderCellOnIdle-on
          - jupyterlab-renderCellOnIdle-off
          - jupyterlab-windowingMode-full
          - jupyterlab-windowingMode-defer
          - jupyterlab-windowingMode-none
          - jupyterlab-1-2
          - retrolab
          - testing
      reference_branch:
        description: "Reference branch on the JupyterLab repository (default: master)"
        required: false
        default: "master"
      reference_project:
        description: "Playwright project to execute on the reference version (if different from the challenger project)"
        required: false
        default: ""
        type: choice
        options:
          - jupyterlab
          - jupyterlab-renderCellOnIdle-on
          - jupyterlab-renderCellOnIdle-off
          - jupyterlab-windowingMode-full
          - jupyterlab-windowingMode-defer
          - jupyterlab-windowingMode-none
          - jupyterlab-1-2
          - retrolab
          - testing
      browser:
        description: "Which browser to use (default 'chromium')"
        required: false
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      samples:
        description: "Number of samples to compute (individual tests multiply this number by their a test-speicific factor)"
        required: false
        default: "100"
        type: string
      grep:
        description: "Tests to include (grep expression)"
        required: false
        default: ""
        type: string
      grep_invert:
        description: "Tests to skip (grep expression)"
        required: false
        default: ""
        type: string

permissions:
  issues: write

jobs:
  test:
    # uses: jupyterlab/benchmarks/.github/workflows/run-profiler.yml@master
    uses: ./.github/workflows/run-profiler.yml
    with:
      event: ${{ github.event_name }}
      challenger: ${{ github.event.inputs.challenger || 'jupyterlab/jupyterlab' }}
      challenger_branch: ${{ github.event.inputs.challenger_branch || 'master' }}
      challenger_project: ${{ github.event.inputs.challenger_project || 'jupyterlab' }}
      reference_branch: ${{ github.event.inputs.reference_branch || 'master' }}
      reference_project: ${{ github.event.inputs.reference_project || github.event.inputs.challenger_project || 'jupyterlab' }}
      browser: ${{ github.event.inputs.browser || 'chromium' }}
      samples: ${{ github.event.inputs.samples || '100' }}
      grep: ${{ github.event.inputs.grep || '' }}
      grep_invert: ${{ github.event.inputs.grep_invert || '' }}
      artifacts_name: 'profiler-report'
